// Generated by `pnpm abi:sync` from smart-contract@f038274f4ddf030135d11adc3d2ca144802f8cbf. Do not edit.
// Only the functions the app calls; the list is in scripts/sync-abis.mjs.
export const collateralPolicyAbi = [
  {
    "type": "function",
    "name": "acceptsNewPositions",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "PoolId"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "termsOf",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "PoolId"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ICollateralPolicy.Terms",
        "components": [
          {
            "name": "maxLtvBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ltBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liquidatorBonusBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "removeHaircutBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "debtCapUsdg",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "minPositionUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "tier",
            "type": "uint8",
            "internalType": "enum ICollateralPolicy.Tier"
          }
        ]
      }
    ],
    "stateMutability": "view"
  }
] as const;
