// Generated by `pnpm abi:sync` from smart-contract@fc982213e0eb13e41d5417c82e6abd59911524b0. Do not edit.
// Only what the app calls or reads; the list is in scripts/sync-abis.mjs.
export const collateralPolicyAbi = [
  {
    "type": "function",
    "name": "acceptsNewPositions",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "PoolId"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "termsOf",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "PoolId"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ICollateralPolicy.Terms",
        "components": [
          {
            "name": "maxLtvBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ltBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liquidatorBonusBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "removeHaircutBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "debtCapUsdg",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "minPositionUsd",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "tier",
            "type": "uint8",
            "internalType": "enum ICollateralPolicy.Tier"
          }
        ]
      }
    ],
    "stateMutability": "view"
  }
] as const;
