// Generated by `pnpm abi:sync` from smart-contract@14341aa33dfea30546d409086c69ca2d3ac384ac. Do not edit.
// Only what the app calls or reads; the list is in scripts/sync-abis.mjs.
export const permit2Abi = [
  {
    "type": "function",
    "name": "nonceBitmap",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  }
] as const;
