// Generated by `pnpm abi:sync` from smart-contract@14341aa33dfea30546d409086c69ca2d3ac384ac. Do not edit.
// Only what the app calls or reads; the list is in scripts/sync-abis.mjs.
export const positionValuerAbi = [
  {
    "type": "function",
    "name": "stateView",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IStateView"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "value",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IPositionValuer.Valuation",
        "components": [
          {
            "name": "liquidity",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "amount0",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amount1",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "fees0",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "fees1",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "principalUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "feesUsd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "spotDeviationBps",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  }
] as const;
