// Generated by `pnpm abi:sync` from smart-contract@fc982213e0eb13e41d5417c82e6abd59911524b0. Do not edit.
// Only what the app calls or reads; the list is in scripts/sync-abis.mjs.
export const priceOracleAbi = [
  {
    "type": "function",
    "name": "record",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;
