// Generated by `pnpm abi:sync` from smart-contract@14341aa33dfea30546d409086c69ca2d3ac384ac. Do not edit.
// Only what the app calls or reads; the list is in scripts/sync-abis.mjs.
export const stateViewAbi = [
  {
    "type": "function",
    "name": "getSlot0",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "PoolId"
      }
    ],
    "outputs": [
      {
        "name": "sqrtPriceX96",
        "type": "uint160",
        "internalType": "uint160"
      },
      {
        "name": "tick",
        "type": "int24",
        "internalType": "int24"
      },
      {
        "name": "protocolFee",
        "type": "uint24",
        "internalType": "uint24"
      },
      {
        "name": "lpFee",
        "type": "uint24",
        "internalType": "uint24"
      }
    ],
    "stateMutability": "view"
  }
] as const;
